# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: jasonroelofs/secrets-fetch-action@do-not-redact-unmasked-secrets
      id: doppler
      with:
        doppler-token: ${{ secrets.DOPPLER_SERVICE_ACCOUNT_TOKEN }}
        doppler-project: example
        doppler-config: dev
    - run: echo "DOPPLER_PROJECT is ${{ steps.doppler.outputs.DOPPLER_PROJECT }} (Doppler meta environment variables are unmasked)"
    - run: echo "HOSTNAME is ${{ steps.doppler.outputs.HOSTNAME }} (should be unmasked)"
    - run: echo "STRIPE_API_KEY is ${{ steps.doppler.outputs.STRIPE_API_KEY }} (should be masked)"
